// Generated by `yarn new:queryMock`
import { server } from '../../server'
import { signInUserQuery } from '../signInUser';
import { Options } from './type'

export const setSignInUserQuery = (options: Options) => {
  server.use(signInUserQuery(options))
}
