// Generated by `yarn new:queryMock`
import { server } from '../../server'
import { getAllContactQuery } from '../getAllContact';
import { Options } from './type'

export const setGetAllContactQuery = (options: Options) => {
  server.use(getAllContactQuery(options))
}
