// Generated by `yarn new:queryMock`
import { GetAllContactQuery as Query } from 'src/graphql/types/index.mock'
import { DeepPartial } from 'utility-types'

export type Options = DeepPartial<Query>
export type { GetAllContactQuery as Query } from 'src/graphql/types/index.mock'
