// Generated by `yarn new:queryMock`
import { getAllContactQuery } from './getAllContact'
import { signInUserQuery } from './signInUser'

export const handlers = [
    getAllContactQuery(),
    signInUserQuery(),
  ]
